import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const autonomous = readFileSync(join(root, "autonomous.js"), "utf8");
const serviceWorker = readFileSync(join(root, "service-worker.js"), "utf8");
const specialist = readFileSync(join(root, "hiep-tuvi-ai.js"), "utf8");
const knowledge = readFileSync(join(root, "hiep-tuvi-knowledge.js"), "utf8");
const stars = readFileSync(join(root, "knowledge/stars.js"), "utf8");
const minorStars = readFileSync(join(root, "knowledge/minor-stars.js"), "utf8");
const allStars = readFileSync(join(root, "knowledge/all-stars.js"), "utf8");
const palaces = readFileSync(join(root, "knowledge/palaces.js"), "utf8");
const combinations = readFileSync(join(root, "knowledge/combinations.js"), "utf8");
const structures = readFileSync(join(root, "knowledge/structures.js"), "utf8");
const bazi = readFileSync(join(root, "knowledge/bazi.js"), "utf8");
const schools = readFileSync(join(root, "knowledge/schools.js"), "utf8");
const browserAi = readFileSync(join(root, "browser-ai.js"), "utf8");
const browserWorker = readFileSync(join(root, "browser-ai-worker.js"), "utf8");
const offline = readFileSync(join(root, "offline-summary.js"), "utf8");
const guard = readFileSync(join(root, "webgpu-failure-guard.js"), "utf8");

assert.match(autonomous, /hiep-tuvi-ai\.js\?v=2\.0\.0/);
assert.match(autonomous, /hiep-tuvi-knowledge\.js\?v=1\.0\.0/);
assert.match(autonomous, /__HIEP_TUVI_CHART__/);
assert.match(autonomous, /HiepTuViKnowledge/);
assert.match(autonomous, /fullReportPlan/);
assert.match(autonomous, /buildFullReportSectionPrompt/);
assert.match(autonomous, /validateFullReportSection/);
assert.match(autonomous, /requestLocalWithFallback/);
assert.match(autonomous, /automatic:\s*true/);
assert.match(autonomous, /scheduleAutomaticReport/);
assert.match(autonomous, /activeRun \+= 1/);
assert.match(autonomous, /AI luận giải lại/);
assert.match(autonomous, /webGpuAvailable/);
assert.doesNotMatch(autonomous, /Phân tích chuyên sâu — 15 bước/);
assert.doesNotMatch(autonomous, /if\s*\(options\.automatic\)\s*return/);

assert.match(browserAi, /Qwen3-4B-q4f16_1-MLC/);
assert.match(browserAi, /Qwen3-8B-q4f16_1-MLC/);
assert.match(browserAi, /Math\.min\(1250/);
assert.match(browserAi, /4096-token context/);
assert.match(browserAi, /new Worker/);
assert.match(browserAi, /type:\s*"module"/);
assert.match(browserWorker, /@mlc-ai\/web-llm@0\.2\.84/);
assert.match(browserWorker, /CreateMLCEngine/);
assert.match(browserWorker, /cacheBackend:\s*"indexeddb"/);
assert.match(browserWorker, /local:\s*true/);

assert.match(serviceWorker, /\.\/hiep-tuvi-knowledge\.js/);
assert.match(serviceWorker, /\.\/knowledge\/stars\.js/);
assert.match(serviceWorker, /\.\/knowledge\/minor-stars\.js/);
assert.match(serviceWorker, /\.\/knowledge\/all-stars\.js/);
assert.match(serviceWorker, /\.\/webgpu-failure-guard\.js/);
assert.match(serviceWorker, /\.\/browser-ai\.js/);
assert.match(serviceWorker, /\.\/browser-ai-worker\.js/);
assert.match(serviceWorker, /tuvi-battu-web-v1\.22-local-full-1/);

assert.match(specialist, /VERSION = "2\.1\.0"/);
assert.match(specialist, /HIEP_TUVI_FULL_REPORT/);
assert.match(specialist, /palaces-6/);
assert.match(specialist, /DATA QUALITY CARD/);
assert.match(specialist, /TỨ TRỤ BÁT TỰ \+ NGŨ HÀNH/);
assert.match(specialist, /RED-TEAM \/ PHẢN BIỆN/);
assert.match(specialist, /HÀNH ĐỘNG THỰC TẾ/);

assert.match(knowledge, /VERSION = "2\.0\.1"/);
assert.match(knowledge, /STRUCTURED_LOCAL_KB/);
assert.match(knowledge, /ruleById/);
assert.match(knowledge, /knowledgeForPalaces/);
assert.match(stars, /STAR-PHAQUAN-001/);
assert.match(stars, /STAR-HOAKY-001/);
assert.match(minorStars, /STAR-LONGDUC-001/);
assert.match(minorStars, /STAR-DAIHAO-001/);
assert.match(allStars, /kb\.stars = Object\.freeze/);
assert.match(palaces, /PAL-MENH-001/);
assert.match(palaces, /Mệnh.*Quan Lộc.*Tài Bạch/);
assert.match(combinations, /COMBO-SATPHATHAM-001/);
assert.match(structures, /complete\|partial\|broken/i);
assert.match(structures, /source layer\/can → carrier star/);
assert.match(structures, /Tuần\/Triệt là bộ điều biến/);
assert.match(bazi, /BAZI-SEASON-001/);
assert.match(bazi, /Không thiếu hành nào bổ hành đó/);
assert.match(schools, /MENH_LY_THIEN_CO/);
assert.match(schools, /source_levels/);

assert.match(offline, /VERSION = "2\.2\.0"/);
assert.match(offline, /XII/);
assert.match(offline, /có tình cảm và nhu cầu gắn kết/);
assert.match(guard, /Invalid ShaderModule|index_kernel/);
assert.match(guard, /WebGPU không tương thích · dùng báo cáo local đầy đủ/);
assert.doesNotMatch(specialist + knowledge + offline, /NHIỆM VỤ BƯỚC/);

console.log("PASS: deterministic local full report is guaranteed while WebGPU AI remains an optional enhancement");
