"use strict";

(function initHiepTuViCombinationData(root) {
  const kb = root.HiepTuViKBData || (root.HiepTuViKBData = {});
  kb.combinations = Object.freeze([
    { id:"COMBO-TUPHUVUTUONG-001", name:"Tử Phủ Vũ Tướng", mandatory_members:["Tử Vi","Thiên Phủ","Vũ Khúc","Thiên Tướng"], retrieval_min:2, required_geometry:"Tùy SCHOOL; phải xác nhận đồng cung/tam hợp/xung chiếu cụ thể trước khi gọi thành cách.", core_function:"Quản trị, trật tự, tài nguyên, tổ chức.", strength_conditions:["đủ thành viên theo SCHOOL","hình học đúng","cát-sát không phá lõi","Tứ Hóa hỗ trợ"], weakening_conditions:["thiếu thành viên","hội yếu","Tuần/Triệt hoặc sát tinh phá node lõi"], rescue_conditions:["Tả Hữu","Khôi Việt","Khoa Quyền Lộc nếu đúng vị trí"], breaking_conditions:["sai hình học","thiếu thành viên bắt buộc","sát tinh/Tuần-Triệt phá điều kiện cốt lõi"], school:"NAM_PHAI_TAM_HOP", source:"HIEP_TUVI_SKILL:star-combinations+formations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-SATPHATHAM-001", name:"Sát Phá Tham", mandatory_members:["Thất Sát","Phá Quân","Tham Lang"], retrieval_min:2, required_geometry:"Kiểm tra tam hợp/đồng cung theo SCHOOL; không suy từ việc chỉ có hai tên sao gần nhau.", core_function:"Biến động, quyết liệt, tái cấu trúc, khai phá, chấp nhận áp lực.", strength_conditions:["thành viên đủ theo hình học","thế đứng phù hợp","Tứ Hóa/cát tinh tạo đầu ra"], weakening_conditions:["hội yếu","Không Kiếp/Kình Đà/Hỏa Linh làm cực đoan mà không có chế hóa","Tuần/Triệt cắt nhịp"], rescue_conditions:["Khoa Quyền Lộc","Tả Hữu","Khôi Việt","Thiên Tướng/Thiên Phủ tùy cấu trúc"], breaking_conditions:["sai hình học","thiếu thành viên lõi"], school:"NAM_PHAI_TAM_HOP", source:"HIEP_TUVI_SKILL:star-combinations+formations", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-CONGUYETDONGLUONG-001", name:"Cơ Nguyệt Đồng Lương", mandatory_members:["Thiên Cơ","Thái Âm","Thiên Đồng","Thiên Lương"], retrieval_min:2, required_geometry:"Phải xác minh hình học theo SCHOOL trước khi gọi cách.", core_function:"Trí, điều phối, phục vụ, ổn định mềm, hệ thống và thích nghi.", strength_conditions:["hình học đúng","các sao có thế đứng phù hợp","ít phá bởi sát tinh nặng"], weakening_conditions:["Cự Môn/Hóa Kỵ hoặc sát tinh làm lệch cơ chế nếu rơi đúng node","Tuần/Triệt làm mất tính liên tục"], rescue_conditions:["Xương Khúc","Khôi Việt","Khoa"], breaking_conditions:["thiếu thành viên chính","sai hình học"], school:"NAM_PHAI_TAM_HOP", source:"HIEP_TUVI_SKILL:star-combinations+formations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-NHATNGUYET-001", name:"Nhật Nguyệt", mandatory_members:["Thái Dương","Thái Âm"], retrieval_min:2, required_geometry:"Đồng cung/hội chiếu phải nêu rõ; vị trí sáng-tối phụ thuộc SCHOOL.", core_function:"Cân bằng biểu hiện công khai và tích lũy/nội tâm.", strength_conditions:["vị trí thuận SCHOOL","cát tinh/Tứ Hóa hỗ trợ"], weakening_conditions:["miếu-hãm bất lợi theo SCHOOL","Hóa Kỵ/sát tinh đánh đúng node"], rescue_conditions:["Xương Khúc","Khoa","Khôi Việt"], breaking_conditions:["không đủ hai sao trong hình học liên quan"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-CUONHAT-001", name:"Cự Nhật", mandatory_members:["Cự Môn","Thái Dương"], retrieval_min:2, required_geometry:"Nêu rõ đồng cung/hội chiếu và cung chủ đề.", core_function:"Biểu đạt, công khai, tranh luận, soi sáng vấn đề.", strength_conditions:["Thái Dương đủ lực","Cự Môn có đầu ra qua Xương Khúc/Khoa","Hóa Kỵ không đánh lõi"], weakening_conditions:["Hóa Kỵ","sát tinh gây xung đột giao tiếp"], rescue_conditions:["Hóa Khoa","Xương Khúc","Khôi Việt"], breaking_conditions:["hai sao không thực sự liên kết hình học"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-COCU-001", name:"Cơ Cự", mandatory_members:["Thiên Cơ","Cự Môn"], retrieval_min:2, required_geometry:"Kiểm tra cung, thế đứng và hình học.", core_function:"Tính toán + ngôn ngữ/nghi vấn; mạnh ở phân tích nhưng dễ phức tạp hóa khi bất lợi.", strength_conditions:["có đầu ra qua Xương Khúc/Khoa","ít Hóa Kỵ/sát tinh phá"], weakening_conditions:["Hóa Kỵ","Không Kiếp/Hỏa Linh làm suy luận gấp hoặc phân tán"], rescue_conditions:["Hóa Khoa","Xương Khúc","Thiên Lương"], breaking_conditions:["không có liên kết hình học rõ"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-COLUONG-001", name:"Cơ Lương", mandatory_members:["Thiên Cơ","Thiên Lương"], retrieval_min:2, required_geometry:"Đồng cung/hội chiếu phải ghi rõ.", core_function:"Mưu lược, điều phối gắn với chuẩn mực và độ bền.", strength_conditions:["ít sát phá","Hóa Khoa/Xương Khúc hỗ trợ"], weakening_conditions:["Hóa Kỵ hoặc sát tinh làm cơ chế mất ổn định"], rescue_conditions:["Khôi Việt","Xương Khúc","Khoa"], breaking_conditions:["không có liên kết hình học"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-VUTHAM-001", name:"Vũ Tham", mandatory_members:["Vũ Khúc","Tham Lang"], retrieval_min:2, required_geometry:"Kiểm tra đồng cung/hội chiếu và cung chủ đề.", core_function:"Thực thi/tài nguyên kết hợp cơ hội, giao tế và ham muốn trải nghiệm.", strength_conditions:["Tài/Quan phù hợp","Lộc/Quyền hỗ trợ","có kỷ luật hóa Tham Lang"], weakening_conditions:["sát tinh/Hóa Kỵ làm tăng cực đoan nguồn lực-ham muốn"], rescue_conditions:["Thiên Phủ","Hóa Khoa","Tả Hữu"], breaking_conditions:["hai sao không liên hệ hình học"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-LIEMTHAM-001", name:"Liêm Tham", mandatory_members:["Liêm Trinh","Tham Lang"], retrieval_min:2, required_geometry:"Kiểm tra cung và chế hóa.", core_function:"Ranh giới/kiểm soát kết hợp ham muốn/giao tế.", strength_conditions:["có kỷ luật/chế hóa","Lộc/Quyền đi đúng node"], weakening_conditions:["Hình Kỵ","đào hoa/sát tinh làm tăng xung đột ranh giới"], rescue_conditions:["Khoa","Thiên Tướng","Tả Hữu"], breaking_conditions:["không liên hệ hình học"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-LIEMSAT-001", name:"Liêm Sát", mandatory_members:["Liêm Trinh","Thất Sát"], retrieval_min:2, required_geometry:"Kiểm tra cung, thế đứng và cát-sát.", core_function:"Quy phạm kết hợp quyết liệt/áp lực; mạnh ở quyết định khó khi có kỷ luật.", strength_conditions:["thế đứng phù hợp","Quyền/Khoa/Tả Hữu hỗ trợ"], weakening_conditions:["Hình Kỵ/Kình Đà/Hỏa Linh quá mạnh","Tuần/Triệt cắt nhịp"], rescue_conditions:["Thiên Tướng","Khoa","Tả Hữu"], breaking_conditions:["không có liên hệ hình học"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },

    { id:"COMBO-KHOAQUYENLOC-001", name:"Khoa Quyền Lộc", mandatory_members:["Hóa Khoa","Hóa Quyền","Hóa Lộc"], retrieval_min:2, required_geometry:"Phải truy được nguồn Hóa, sao mang Hóa và mức hội tụ vào trục chủ đề.", core_function:"Nguồn lực + quyền tác động + chuẩn hóa/danh tiếng.", strength_conditions:["hội tụ đúng trục","carrier star phù hợp","không bị Triệt/sát tinh phá nặng"], weakening_conditions:["phân tán ở các miền xung đột","nguồn Hóa khác tầng bị trộn"], rescue_conditions:[], breaking_conditions:["không truy được nguồn Hóa","trộn nguyên cục với lưu vận"], school:"TU_HOA", source:"HIEP_TUVI_SKILL:star-combinations+tu-hoa", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-LOCMA-001", name:"Lộc Mã", mandatory_members:["Thiên Mã","Lộc Tồn","Hóa Lộc"], retrieval_min:2, required_geometry:"Nguồn lực và động phải thật sự liên kết cung/hình học.", core_function:"Nguồn lực kết hợp dịch chuyển/động lực thay đổi môi trường.", strength_conditions:["Lộc và Mã cùng hướng vào trục Tài/Quan/Di","không bị phá mạnh"], weakening_conditions:["Mã động nhưng Lộc phân tán","Triệt/sát tinh cắt nhịp"], rescue_conditions:["Khoa/Quyền","Tả Hữu"], breaking_conditions:["chỉ có tên sao nhưng không liên hệ hình học"], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"CONDITIONAL" },
    { id:"COMBO-XUONGKHUC-001", name:"Xương Khúc", mandatory_members:["Văn Xương","Văn Khúc"], retrieval_min:2, required_geometry:"Đồng cung/hội chiếu phải ghi rõ.", core_function:"Học thuật, biểu đạt, kỹ năng văn bản/nghệ thuật.", strength_conditions:["đi với chính tinh có đầu ra học thuật/biểu đạt","Khoa/Khôi Việt hỗ trợ"], weakening_conditions:["Hóa Kỵ/sát tinh làm tăng phức tạp hoặc tranh chấp biểu đạt"], rescue_conditions:["Hóa Khoa","Khôi Việt"], breaking_conditions:[], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-KHOIVIET-001", name:"Khôi Việt", mandatory_members:["Thiên Khôi","Thiên Việt"], retrieval_min:2, required_geometry:"Đồng cung/hội chiếu.", core_function:"Cơ hội, người hỗ trợ, khả năng được nhìn thấy/nâng đỡ.", strength_conditions:["cấu trúc chính có nền","đúng cung chủ đề"], weakening_conditions:["không thể cứu một cấu trúc lõi bị phá hoàn toàn"], rescue_conditions:[], breaking_conditions:[], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-TAHUU-001", name:"Tả Hữu", mandatory_members:["Tả Phù","Hữu Bật"], retrieval_min:2, required_geometry:"Đồng cung/hội chiếu.", core_function:"Trợ lực, phối hợp, nguồn lực phụ trợ.", strength_conditions:["cấu trúc chính có khả năng nhận trợ lực"], weakening_conditions:["không đủ để đảo một node lõi bị phá"], rescue_conditions:[], breaking_conditions:[], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-KHONGKIEP-001", name:"Không Kiếp", mandatory_members:["Địa Không","Địa Kiếp"], retrieval_min:2, required_geometry:"Xác định đang đồng cung/hội chiếu và node nào bị tác động.", core_function:"Đứt gãy, rỗng hụt, cực đoan hoặc biến đổi mạnh.", strength_conditions:[], weakening_conditions:["đánh vào chính tinh/bộ sao vốn yếu","gặp Hóa Kỵ hoặc Hỏa Linh/Kình Đà không chế"], rescue_conditions:["Thiên Phủ/Thiên Lương/Khoa tùy cấu trúc","Tuần/Triệt có thể đổi nhịp chứ không tự động hóa giải"], breaking_conditions:[], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-KINHDA-001", name:"Kình Đà", mandatory_members:["Kình Dương","Đà La"], retrieval_min:2, required_geometry:"Xác định node chịu áp lực trực diện/trì kéo.", core_function:"Áp lực trực diện kết hợp ma sát kéo dài.", strength_conditions:[], weakening_conditions:["đánh đúng node vốn yếu","không có chế hóa"], rescue_conditions:["Tả Hữu/Khoa/Thiên Tướng tùy cung"], breaking_conditions:[], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-HOALINH-001", name:"Hỏa Linh", mandatory_members:["Hỏa Tinh","Linh Tinh"], retrieval_min:2, required_geometry:"Xác định nơi kích hoạt và chính tinh bị tác động.", core_function:"Bộc phát, tốc độ, nhiệt và biến đổi đột ngột theo ngôn ngữ truyền thống.", strength_conditions:[], weakening_conditions:["đi với bộ sao vốn cực đoan","không có chế hóa"], rescue_conditions:["Khoa/Tả Hữu/Thiên Lương tùy node"], breaking_conditions:[], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:star-combinations", source_level:"C", confidence:"SUPPORTED" },
    { id:"COMBO-HINHKY-001", name:"Hình Kỵ", mandatory_members:["Thiên Hình","Hóa Kỵ"], retrieval_min:2, required_geometry:"Xác định cung/node và nguồn Hóa Kỵ.", core_function:"Quy phạm/cắt kết hợp ma sát, ám ảnh hoặc điểm phải trả giá/chú ý.", strength_conditions:[], weakening_conditions:["đánh vào cung Tật/Quan/Phu hoặc node vốn bất ổn nhưng phải đọc toàn cấu trúc"], rescue_conditions:["Khoa/Thiên Lương/Thiên Tướng tùy bối cảnh"], breaking_conditions:["không truy được nguồn Hóa Kỵ"], school:"TU_HOA", source:"HIEP_TUVI_SKILL:star-combinations+tu-hoa", source_level:"C", confidence:"CONDITIONAL" }
  ]);
})(typeof globalThis !== "undefined" ? globalThis : this);
