"use strict";

(function initHiepTuViMinorStarData(root) {
  const kb = root.HiepTuViKBData || (root.HiepTuViKBData = {});
  kb.minorStars = Object.freeze([
    { id:"STAR-LONGDUC-001", name:"Long Đức", group:"support", native_meaning:"Thiện ý, mềm hóa xung đột, khả năng giữ tình cảm và giảm độ gay gắt của một số cấu trúc.", must_check:["cung","chính tinh","sát tinh","Tứ Hóa"], exceptions:["Không xóa Hóa Kỵ hay sát tinh nặng."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENDUC-001", name:"Thiên Đức", group:"support", native_meaning:"Phúc trợ, xu hướng giảm cực đoan và tạo khoảng đệm trong tương tác.", must_check:["cung","cấu trúc chính"], exceptions:["Không phải nút giải tuyệt đối."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-NGUYETDUC-001", name:"Nguyệt Đức", group:"support", native_meaning:"Mềm hóa, thiện chí, khả năng hòa giải hoặc nhận trợ lực trong quan hệ.", must_check:["cung","cấu trúc chính"], exceptions:["Không phủ định áp lực lõi."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENQUAN-001", name:"Thiên Quan", group:"support", native_meaning:"Trợ lực, cơ hội được hỗ trợ hoặc được hướng dẫn theo diễn giải truyền thống.", must_check:["cung","chính tinh"], exceptions:["Không tự động tạo kết quả thực tế."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENPHUC-001", name:"Thiên Phúc", group:"support", native_meaning:"Phúc trợ, khả năng nhận sự giúp đỡ hoặc giảm độ gắt của tình huống.", must_check:["cung","chính tinh"], exceptions:["Không xóa cấu trúc bất lợi."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-LONGTRI-001", name:"Long Trì", group:"support", native_meaning:"Trợ lực về vị thế, nề nếp, sự nâng đỡ hoặc tính trang trọng của môi trường.", must_check:["cung","Phượng Các","chính tinh"], exceptions:["Không đồng nghĩa địa vị cao."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-PHUONGCAC-001", name:"Phượng Các", group:"support", native_meaning:"Tính chỉnh chu, biểu đạt, thẩm mỹ và trợ lực xã hội theo ngữ cảnh.", must_check:["cung","Long Trì","Xương Khúc"], exceptions:["Không tự động tạo danh tiếng."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-GIAITHAN-001", name:"Giải Thần", group:"support", native_meaning:"Khả năng tháo gỡ, giảm độ bế tắc hoặc tạo phương án xử lý khi có cấu trúc hỗ trợ.", must_check:["cung","node bị áp lực"], exceptions:["Không vô hiệu hóa sát tinh hay Hóa Kỵ."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENGIAI-001", name:"Thiên Giải", group:"support", native_meaning:"Lớp cứu giải/phương án giảm áp theo diễn giải truyền thống.", must_check:["cung","node bị áp lực"], exceptions:["Không phải cơ chế cứu tuyệt đối."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-DIAGIAI-001", name:"Địa Giải", group:"support", native_meaning:"Lớp giảm áp hoặc tạo đường xử lý thực tế hơn trong một số cấu trúc.", must_check:["cung","node bị áp lực"], exceptions:["Không tự động biến xấu thành tốt."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },

    { id:"STAR-DAIHAO-001", name:"Đại Hao", group:"pressure", native_meaning:"Tiêu hao nguồn lực, chi phí lớn, nhịp ra-vào mạnh hoặc khó giữ ổn định nếu cấu trúc quản trị yếu.", must_check:["cung","Tài-Điền","Lộc","Tứ Hóa"], exceptions:["Không đồng nghĩa mất tiền hay phá sản chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-TIEUHAO-001", name:"Tiểu Hao", group:"pressure", native_meaning:"Tiêu hao nhỏ, chi phí lặp lại hoặc thất thoát vụn cần được quản trị.", must_check:["cung","nguồn lực"], exceptions:["Không đồng nghĩa tổn thất chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-BACHHO-001", name:"Bạch Hổ", group:"pressure", native_meaning:"Sức ép, tính quyết liệt, va chạm hoặc tín hiệu cần thận trọng theo diễn giải truyền thống.", must_check:["cung","sát tinh","Tật Ách","vận"], exceptions:["Không dùng để chẩn đoán bệnh hay dự báo tai nạn chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-TANGMON-001", name:"Tang Môn", group:"pressure", native_meaning:"Tâm trạng nặng, trách nhiệm, lo toan hoặc bối cảnh dễ mang cảm giác áp lực theo ngôn ngữ truyền thống.", must_check:["cung","chính tinh","vận"], exceptions:["Không suy tang sự hay biến cố bắt buộc."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENKHOC-001", name:"Thiên Khốc", group:"pressure", native_meaning:"Độ nhạy cảm, cảm giác thiếu thỏa mãn hoặc áp lực cảm xúc cần được đặt trong toàn cấu trúc.", must_check:["cung","Thiên Hư","chính tinh"], exceptions:["Không đồng nghĩa buồn khổ chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENHU-001", name:"Thiên Hư", group:"pressure", native_meaning:"Khoảng hụt, kỳ vọng không khớp hoặc cảm giác thiếu chắc chắn trong một số chủ đề.", must_check:["cung","Thiên Khốc","chính tinh"], exceptions:["Không đồng nghĩa thất bại hay mất mát chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-COTHAN-001", name:"Cô Thần", group:"pressure", native_meaning:"Xu hướng tự xử lý, giữ khoảng cách hoặc khó chia sẻ ngay trong một số hoàn cảnh.", must_check:["cung","Quả Tú","chính tinh"], exceptions:["Không kết luận cô độc hay không kết hôn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-QUATU-001", name:"Quả Tú", group:"pressure", native_meaning:"Khuynh hướng thu mình, độc lập hoặc ít bộc lộ nhu cầu trong một số bối cảnh.", must_check:["cung","Cô Thần","chính tinh"], exceptions:["Không kết luận cô độc hay hôn nhân xấu."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENKHONG-001", name:"Thiên Không", group:"pressure", native_meaning:"Khoảng trống, đổi pha, kỳ vọng bị phá vỡ hoặc nhu cầu tái cấu trúc.", must_check:["cung","Không Kiếp","Tứ Hóa"], exceptions:["Không đồng nghĩa mất hết hay tai họa chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-KIEPSAT-001", name:"Kiếp Sát", group:"pressure", native_meaning:"Tín hiệu áp lực và rủi ro cần tăng kiểm soát trong ngôn ngữ truyền thống.", must_check:["cung","sát tinh","vận"], exceptions:["Không dùng để dự báo tai nạn, tội phạm hay tai họa chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"WEAK" },
    { id:"STAR-PHATOAI-001", name:"Phá Toái", group:"pressure", native_meaning:"Nhiễu, việc vụn, lỗi nhỏ hoặc những yếu tố làm giảm tính liền mạch của kế hoạch.", must_check:["cung","chính tinh"], exceptions:["Không đồng nghĩa đổ vỡ lớn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"WEAK" },
    { id:"STAR-QUANPHU-001", name:"Quan Phù", group:"pressure", native_meaning:"Quy trình, tranh luận, giấy tờ hoặc ma sát liên quan quy tắc khi bối cảnh phù hợp.", must_check:["cung","Cự Môn","Thiên Hình","Tứ Hóa"], exceptions:["Không kết luận kiện tụng hay phạm pháp chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THAITUE-001", name:"Thái Tuế", group:"pressure", native_meaning:"Tăng tính nổi bật, áp lực thể hiện hoặc xung động của chủ đề cung theo hệ truyền thống.", must_check:["cung","chính tinh","vận"], exceptions:["Không tự động đồng nghĩa xấu."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" }
  ]);
})(typeof globalThis !== "undefined" ? globalThis : this);
