"use strict";

(function initHiepTuViStarData(root) {
  const kb = root.HiepTuViKBData || (root.HiepTuViKBData = {});
  kb.stars = Object.freeze([
    { id:"STAR-TUVI-001", name:"Tử Vi", group:"main", native_meaning:"Chủ trục, điều phối, vị thế, khả năng quy tụ và chịu trách nhiệm.", must_check:["cung","miếu-hãm","bộ sao","tam phương","Tứ Hóa","Tuần/Triệt","Mệnh-Thân"], exceptions:["Không đồng nghĩa quyền lực thực tế nếu cấu trúc không hỗ trợ."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THIENCO-001", name:"Thiên Cơ", group:"main", native_meaning:"Tính toán, phương án, thay đổi, kỹ thuật, cơ biến, tư duy chiến lược.", must_check:["cung","thế đứng","Cơ Cự/Cơ Lương/Cơ Nguyệt Đồng Lương","Tứ Hóa","sát tinh"], exceptions:["Không tự động đồng nghĩa nghề kỹ thuật hoặc hay thay đổi."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THAIDUONG-001", name:"Thái Dương", group:"main", native_meaning:"Biểu hiện ra ngoài, chủ động, danh tiếng, soi sáng, tính công khai.", must_check:["vị trí","miếu-hãm","Nhật Nguyệt/Cự Nhật","Tứ Hóa","tam phương"], exceptions:["Không dùng sáng/tối như phán tốt-xấu tuyệt đối."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-VUKHUC-001", name:"Vũ Khúc", group:"main", native_meaning:"Thực thi, tài chính, kỷ luật, định lượng và chịu áp lực.", must_check:["cung","Vũ Tham/Tử Phủ Vũ Tướng","Tứ Hóa","sát tinh","Mệnh-Tài-Quan"], exceptions:["Không kết luận giàu chỉ vì Vũ Khúc."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THIENDONG-001", name:"Thiên Đồng", group:"main", native_meaning:"Thích nghi, hưởng thụ, phúc khí, mềm dẻo, thay đổi theo hoàn cảnh.", must_check:["cung","Cơ Nguyệt Đồng Lương","Tứ Hóa","sát tinh","Tràng Sinh"], exceptions:["Không đồng nghĩa yếu đuối hoặc nhàn hạ chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-LIEMTRINH-001", name:"Liêm Trinh", group:"main", native_meaning:"Nguyên tắc, ranh giới, ham muốn, kiểm soát, cạnh tranh và tính quy phạm.", must_check:["cung","Liêm Tham/Liêm Sát","Tứ Hóa","Hình Kỵ","tam phương"], exceptions:["Không suy đạo đức hay vi phạm pháp luật từ một sao."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THIENPHU-001", name:"Thiên Phủ", group:"main", native_meaning:"Tích trữ, quản trị, giữ nguồn lực, ổn định và khả năng bảo toàn.", must_check:["cung","Tử Phủ Vũ Tướng","sát tinh","Tuần/Triệt","Tài-Điền"], exceptions:["Không đồng nghĩa tài sản lớn nếu không có cấu trúc nguồn lực."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THAIAM-001", name:"Thái Âm", group:"main", native_meaning:"Tài nguyên, tích lũy, nội tâm, quan sát, tính kín và khả năng nuôi dưỡng.", must_check:["vị trí","miếu-hãm","Nhật Nguyệt","Cơ Nguyệt Đồng Lương","Tứ Hóa"], exceptions:["Không đồng nghĩa giàu, nữ tính hay nội tâm theo nghĩa tâm lý học."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THAMLANG-001", name:"Tham Lang", group:"main", native_meaning:"Ham muốn, giao tế, thu hút, khai thác cơ hội, đa tài và trải nghiệm.", must_check:["cung","Sát Phá Tham/Vũ Tham/Liêm Tham","đào hoa","Tứ Hóa","sát tinh"], exceptions:["Không suy ngoại tình, nghiện hay tham lam như fact."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-CUMON-001", name:"Cự Môn", group:"main", native_meaning:"Ngôn ngữ, tranh luận, nghi vấn, phân tích; thị phi chỉ khi cấu trúc bất lợi.", must_check:["cung","Cơ Cự/Cự Nhật","Hóa Kỵ","Xương Khúc","tam phương"], exceptions:["Không tự động kết luận khẩu thiệt/thị phi."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THIENTUONG-001", name:"Thiên Tướng", group:"main", native_meaning:"Hỗ trợ, điều phối, bảo hộ, quy trình, vai trò trung gian/đại diện.", must_check:["cung","Tử Phủ Vũ Tướng","đối cung","Tứ Hóa","sát tinh"], exceptions:["Không đồng nghĩa luôn được bảo hộ hoặc có chức vụ."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THIENLUONG-001", name:"Thiên Lương", group:"main", native_meaning:"Nguyên tắc, che chở, chuẩn mực, cứu giải, kinh nghiệm và tính bền.", must_check:["cung","Cơ Lương/Cơ Nguyệt Đồng Lương","Tứ Hóa","sát tinh","Phúc-Tật"], exceptions:["Không dùng như nút xóa rủi ro."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-THATSAT-001", name:"Thất Sát", group:"main", native_meaning:"Quyết đoán, áp lực, cắt bỏ, mạo hiểm có kiểm soát, quyền lực trong hoàn cảnh khó.", must_check:["cung","Sát Phá Tham/Liêm Sát","miếu-hãm","sát tinh","Tứ Hóa","Triệt"], exceptions:["Không đồng nghĩa hung họa hay bạo lực."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },
    { id:"STAR-PHAQUAN-001", name:"Phá Quân", group:"main", native_meaning:"Phá cũ, tái cấu trúc, thử nghiệm, biến động, chấp nhận chi phí chuyển đổi.", must_check:["cung","Sát Phá Tham","miếu-hãm","Tứ Hóa","Tuần/Triệt","Mệnh-Tài-Quan"], exceptions:["Không đồng nghĩa thất bại, phá sản hoặc phá hoại."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:main-stars", source_level:"C", confidence:"CORE" },

    { id:"STAR-TAPHU-001", name:"Tả Phù", group:"support", native_meaning:"Hỗ trợ, phối hợp, nguồn lực phụ trợ.", must_check:["cấu trúc chính","Tả Hữu","cung"], exceptions:["Không cộng điểm cơ học."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-HUUBAT-001", name:"Hữu Bật", group:"support", native_meaning:"Hỗ trợ, phối hợp, nguồn lực phụ trợ.", must_check:["cấu trúc chính","Tả Hữu","cung"], exceptions:["Không cộng điểm cơ học."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-VANXUONG-001", name:"Văn Xương", group:"support", native_meaning:"Học thuật, biểu đạt, kỹ năng văn bản/nghệ thuật.", must_check:["Xương Khúc","cung","Tứ Hóa","sát tinh"], exceptions:["Có thể làm mạnh cả năng lực lẫn độ phức tạp."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-VANKHUC-001", name:"Văn Khúc", group:"support", native_meaning:"Học thuật, biểu đạt, kỹ năng văn bản/nghệ thuật.", must_check:["Xương Khúc","cung","Tứ Hóa","sát tinh"], exceptions:["Có thể làm mạnh cả năng lực lẫn độ phức tạp."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-THIENKHOI-001", name:"Thiên Khôi", group:"support", native_meaning:"Cơ hội, người hỗ trợ, khả năng được nhìn thấy/nâng đỡ theo quan niệm truyền thống.", must_check:["Khôi Việt","cung","cấu trúc chính"], exceptions:["Không xóa cấu trúc yếu."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-THIENVIET-001", name:"Thiên Việt", group:"support", native_meaning:"Cơ hội, người hỗ trợ, khả năng được nhìn thấy/nâng đỡ theo quan niệm truyền thống.", must_check:["Khôi Việt","cung","cấu trúc chính"], exceptions:["Không xóa cấu trúc yếu."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-ANQUANG-001", name:"Ân Quang", group:"support", native_meaning:"Phúc trợ/cứu giải theo nhiều truyền thống.", must_check:["cung","cấu trúc chính"], exceptions:["Không xóa toàn bộ bất lợi."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENQUY-001", name:"Thiên Quý", group:"support", native_meaning:"Phúc trợ/cứu giải theo nhiều truyền thống.", must_check:["cung","cấu trúc chính"], exceptions:["Không xóa toàn bộ bất lợi."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-LOCTON-001", name:"Lộc Tồn", group:"resource", native_meaning:"Tài nguyên, duy trì, tích lũy.", must_check:["cung","Lộc Mã","Tứ Hóa","Tài-Điền"], exceptions:["Không đồng nghĩa giàu chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-THIENMA-001", name:"Thiên Mã", group:"movement", native_meaning:"Dịch chuyển, động lực, thay đổi môi trường.", must_check:["cung","Lộc Mã","tam phương","vận"], exceptions:["Không tự động đồng nghĩa đi xa hay phát tài."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },

    { id:"STAR-DAOHOA-001", name:"Đào Hoa", group:"social", native_meaning:"Sức hút, quan hệ, cảm xúc, biểu hiện xã hội.", must_check:["cung","đào-hồng-hỷ","chính tinh","Tứ Hóa"], exceptions:["Không kết luận ngoại tình hoặc đạo đức."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-HONGLOAN-001", name:"Hồng Loan", group:"social", native_meaning:"Sức hút, quan hệ, cảm xúc, biểu hiện xã hội.", must_check:["cung","đào-hồng-hỷ","chính tinh"], exceptions:["Không kết luận hôn nhân chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENHY-001", name:"Thiên Hỷ", group:"social", native_meaning:"Hỷ khí, kết nối, biểu hiện xã hội.", must_check:["cung","đào-hồng-hỷ","chính tinh"], exceptions:["Chỉ là modifier, không phải verdict."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },
    { id:"STAR-THIENDIEU-001", name:"Thiên Diêu", group:"social", native_meaning:"Sức hút, cảm xúc, biểu hiện xã hội.", must_check:["cung","chính tinh","cát-sát"], exceptions:["Không dùng để quy kết hành vi quan hệ."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },

    { id:"STAR-KINHDUONG-001", name:"Kình Dương", group:"pressure", native_meaning:"Cạnh tranh, cản lực, sức ép trực diện.", must_check:["Kình Đà","cung","sao bị tác động","cứu/chế"], exceptions:["Không đồng nghĩa tai nạn hay bạo lực chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-DALA-001", name:"Đà La", group:"pressure", native_meaning:"Cản lực, trì kéo, ma sát kéo dài.", must_check:["Kình Đà","cung","sao bị tác động","cứu/chế"], exceptions:["Không đồng nghĩa trì trệ tuyệt đối."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-HOATINH-001", name:"Hỏa Tinh", group:"pressure", native_meaning:"Bộc phát, tốc độ, nhiệt, biến đổi đột ngột theo quan niệm truyền thống.", must_check:["Hỏa Linh","cung","chính tinh","cứu/chế"], exceptions:["Không dùng để dự báo tai họa chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-LINHTINH-001", name:"Linh Tinh", group:"pressure", native_meaning:"Bộc phát, tốc độ, nhiệt, biến đổi đột ngột theo quan niệm truyền thống.", must_check:["Hỏa Linh","cung","chính tinh","cứu/chế"], exceptions:["Không dùng để dự báo tai họa chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-DIAKHONG-001", name:"Địa Không", group:"pressure", native_meaning:"Đứt gãy, rỗng hụt, cực đoan hoặc biến đổi mạnh.", must_check:["Không Kiếp","cung","cấu trúc bị phá","cứu/chế"], exceptions:["Không đồng nghĩa tai họa chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-DIAKIEP-001", name:"Địa Kiếp", group:"pressure", native_meaning:"Đứt gãy, rỗng hụt, cực đoan hoặc biến đổi mạnh.", must_check:["Không Kiếp","cung","cấu trúc bị phá","cứu/chế"], exceptions:["Không đồng nghĩa tai họa chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"SUPPORTED" },
    { id:"STAR-THIENHINH-001", name:"Thiên Hình", group:"pressure", native_meaning:"Cắt, quy phạm, kỹ thuật, hình pháp/va chạm theo ngữ cảnh.", must_check:["Hình Kỵ","cung","chính tinh","Tứ Hóa"], exceptions:["Không suy phạm tội hoặc kiện tụng chắc chắn."], school:"CLASSICAL", source:"HIEP_TUVI_SKILL:auxiliary-stars", source_level:"C", confidence:"CONDITIONAL" },

    { id:"STAR-HOALOC-001", name:"Hóa Lộc", group:"transformation", native_meaning:"Khuynh hướng tăng nguồn lực, thu hút, lợi ích theo ngữ cảnh.", must_check:["nguồn Hóa","sao mang Hóa","cung đích","hình học","bộ sao"], exceptions:["Không đồng nghĩa giàu hoặc đại cát chắc chắn."], school:"TU_HOA", source:"HIEP_TUVI_SKILL:tu-hoa", source_level:"C", confidence:"CORE" },
    { id:"STAR-HOAQUYEN-001", name:"Hóa Quyền", group:"transformation", native_meaning:"Quyền tác động, kiểm soát, sức đẩy, trách nhiệm.", must_check:["nguồn Hóa","sao mang Hóa","cung đích","hình học","bộ sao"], exceptions:["Không đồng nghĩa chức quyền thực tế."], school:"TU_HOA", source:"HIEP_TUVI_SKILL:tu-hoa", source_level:"C", confidence:"CORE" },
    { id:"STAR-HOAKHOA-001", name:"Hóa Khoa", group:"transformation", native_meaning:"Chuẩn hóa, học thức/danh tiếng, giảm ma sát trong một số cấu trúc.", must_check:["nguồn Hóa","sao mang Hóa","cung đích","hình học"], exceptions:["Không phải nút cứu giải tuyệt đối."], school:"TU_HOA", source:"HIEP_TUVI_SKILL:tu-hoa", source_level:"C", confidence:"CORE" },
    { id:"STAR-HOAKY-001", name:"Hóa Kỵ", group:"transformation", native_meaning:"Nút ma sát, ám ảnh, trì trệ, sai lệch hoặc nơi phải trả giá/chú ý.", must_check:["nguồn Hóa","sao mang Hóa","cung đích","hình học","node vốn yếu"], exceptions:["Không đồng nghĩa tai họa, bệnh hay phá sản chắc chắn."], school:"TU_HOA", source:"HIEP_TUVI_SKILL:tu-hoa", source_level:"C", confidence:"CORE" }
  ]);
})(typeof globalThis !== "undefined" ? globalThis : this);
